plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
}

sourceCompatibility = targetCompatibility = '1.8'
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":phantomshield-annotations")
    implementation project(":phantomshield-inline")
    implementation project(":phantomshield-internals")

    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

jar {
    archiveFileName.set('phantomshield-verification.bin');
}

task copyToObfuscator(type: Copy) {
    from 'build/libs/phantomshield-verification.bin'
    into '../phantomshield-obfuscator/src/main/resources/binaries/'
}
jar.finalizedBy(copyToObfuscator)