package tech.skidonion.obfuscator.utils;

import org.clyze.jphantom.ClassMembers;
import org.clyze.jphantom.hier.ClassHierarchy;
import org.clyze.jphantom.hier.IncrementalClassHierarchy;
import org.objectweb.asm.*;

import java.io.IOException;
import java.io.InputStream;
import java.util.Enumeration;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;

import static tech.skidonion.obfuscator.PhantomShield.ERROR;
import static tech.skidonion.obfuscator.PhantomShield.TRANSLATION;

public class JPhantomUtils {
    public static final Type OBJECT_TYPE = Type.getObjectType("java/lang/Object");

    /**
     * This is copy pasted from JPhantom, modified to be more lenient towards obfuscated inputs.
     *
     * @param file Some jar file.
     * @return Class hierarchy.
     * @throws IOException When the archive cannot be read.
     */
    public static ClassHierarchy clsHierarchyFromArchive(JarFile file) throws IOException {
        try {
            ClassHierarchy hierarchy = new IncrementalClassHierarchy();
            for (Enumeration<JarEntry> e = file.entries(); e.hasMoreElements(); ) {
                JarEntry entry = e.nextElement();
                if (entry.isDirectory())
                    continue;
                if (!entry.getName().endsWith(".class"))
                    continue;
                try (InputStream stream = file.getInputStream(entry)) {
                    ClassReader reader = new ClassReader(stream);
                    String[] ifaceNames = reader.getInterfaces();
                    Type clazz = Type.getObjectType(reader.getClassName());
                    Type superclass = reader.getSuperName() == null
                            ? OBJECT_TYPE
                            : Type.getObjectType(reader.getSuperName());
                    Type[] ifaces = new Type[ifaceNames.length];
                    for (int i = 0; i < ifaces.length; i++)
                        ifaces[i] = Type.getObjectType(ifaceNames[i]);
                    // Add type to hierarchy
                    boolean isInterface = (reader.getAccess() & Opcodes.ACC_INTERFACE) != 0;
                    try {
                        if (isInterface) {
                            hierarchy.addInterface(clazz, ifaces);
                        } else {
                            hierarchy.addClass(clazz, superclass, ifaces);
                        }
                    } catch (Exception ex) {
                        ERROR(TRANSLATION("phantom-shield-x.jphantom.error1"), clazz, ex);
                    }
                } catch (IOException ex) {
                    ERROR(TRANSLATION("phantom-shield-x.jphantom.error2"), file.getName(), ex);
                }
            }
            return hierarchy;
        } finally {
            file.close();
        }
    }

    /**
     * Adds a note to the given class that it has been auto-generated.
     *
     * @param generated Input generated JPhantom class.
     * @return modified class that clearly indicates it is generated.
     */
    public static byte[] decorate(byte[] generated) {
        ClassWriter cw = new ClassWriter(0);
        ClassVisitor cv = new ClassVisitor(Opcodes.ASM9, cw) {
            @Override
            public void visitEnd() {
                visitAnnotation("LAutoGenerated;", true)
                        .visit("msg", "JPhantom automatically generated this class");
                super.visitEnd();
            }
        };
        new ClassReader(generated).accept(cv, ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);
        return cw.toByteArray();
    }
}
